### ISSUE TITLE
Rezept für Charcoal in NEI crashed den Client

### ISSUE THREAD

**Issue by krakel** [Nedelosk/Modular-Machines#19]
Ich wollte mir das Rezept zu Charcoal anschauen.

```
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
    at nedelosk.forestday.common.plugins.nei.machines.CharcoalKilnHandler.loadCraftingRecipes(CharcoalKilnHandler.java:71)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327)
    at nedelosk.forestday.common.plugins.nei.machines.CharcoalKilnHandler.loadCraftingRecipes(CharcoalKilnHandler.java:104)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 32 more
Caused by: java.lang.NullPointerException
```

**Comment by Nedelosk** [comment]
Ach immer diese Imports. Naja schon gefixt.
